### ISSUE TITLE
Default ACL when writing files

### ISSUE THREAD

**Issue by Vizualni** [fclairamb/afero-s3#181]
Would it be possible to add a way to set the ACL on newly created objects? For example, I am using Digital Ocean Spaces and I am uploading files that should be accessible by the general public. By default, those files have the ACL set to `Private`, while I would benefit from having this set to `Public` (by setting the appropriate AWS S3 setting for the ACL that DO understands since DO Spaces follows the AWS S3 api).
I propose that during the Fs initialization we could set the default ACL that would get applied when [writing to a file](github.com/fclairamb/afero-s3). I am open to suggestions.

If that sounds OK, I'd be more than happy to implement this if you're busy.

**Comment by fclairamb** [comment]
Hi @Vizualni,

I think supporting both is a good idea:
- Having it on the driver setup works fine and is easy to do
- It would probably also make more sense to use the "other" part of the chmod command to change the ACL rights of specific files. It would be better to keep it consistent with reads (on file listing for example), but then that would mean performing a new API call per file.
