### ISSUE TITLE
All files uploaded to S3 with Content-Type binary/octet-stream

### ISSUE THREAD

**Issue by cablespaghetti** [fclairamb/afero-s3#190]
All files are uploaded with a Content-Type of binary/octetstream. This is a problem for our use case where we're uploading to a bucket which is used for hosting files for a website. I believe there is functionality in the SDK to auto-detect the Content-Type based on the file extension which might be a better default.

**Comment by fclairamb** [comment]
>  I believe there is functionality in the SDK to auto-detect the Content-Type based on the file extension which might be a better default.

I don't think this exists.

I could add some file extension to mime type [quite easily](https://golang.org/pkg/mime/#TypeByExtension).

**Comment by fclairamb** [comment]
This is fixed with #209.

Thank you for your feedback !

**Comment by cablespaghetti** [comment]
Amazing. Thanks!
