### ISSUE TITLE
bug: File.Readdir appends trailing slash even if there is already one present

### ISSUE THREAD

**Issue by blockloop** [fclairamb/afero-s3#321]
https://github.com/fclairamb/afero-s3/blob/a24edce4fd30a379d12581a2c1f9b9651b35679a/s3_file.go#L74

If I call `f.Readdir` where `f.name` is `/Path/` then it appends another slash to make it `/Path//` which fails
in s3/minio/etc.

**Comment by fclairamb** [comment]
Thank you very much @blockloop ! And sorry for the very late answer.

**Comment by blockloop** [comment]
No problem. Thank you
